set nocompatible

" Bootstrap this vim directory. see bootstrap.vim.
" It is necessary to export environment variables as follows:
" export MYVIMRC='path-to-this-file'
" export VIMINIT='source "$MYVIMRC"'

execute 'source '.expand('<sfile>:p:h').'/bootstrap.vim'

" ================== preamble ===================

" These define the 'interface' with which one could customize all the following features (they adhere to the conventions made in config-default.vim)

" load Plugin infrastructure

call Src('plug-bootstrap.vim')
call Src('rc/plugins.vim')

" ------------------ basically everything else in happy semiorderly fashion ----

if ! empty(g:adhocinitfile)
    if filereadable(g:adhocinitfile)
        execute 'source ' . fnameescape(g:adhocinitfile)
    endif
endif

call Src('rc/generalfuncs.vim')
call Src('rc/basics.vim')
call Src('rc/basicmaps.vim')

call Src('rc/dropnewstuffhere.vim')

" call Src('crutches/gvim-emulate-alt-term-behavior.vim')
call Src('rc/dirvish.vim')
call Src('rc/ycm.vim')
call Src('rc/args.vim')
call Src('rc/ale.vim')
call Src('rc/fzf.vim')
call Src('rc/motion_easy.vim')
call Src('rc/copypaste.vim')
call Src('rc/vsearch.vim')
" call Src('rc/schlepp.vim')
call Src('rc/ranger.vim')
call Src('rc/appearance.vim')
call Src('rc/generalfuncs.vim')
call Src('rc/termrelated.vim')
" call Src('rc/bookmarks.vim')
call Src('rc/snippets.vim')
call Src('rc/scratch.vim')
call Src('rc/expand-region.vim')
call Src('rc/goldenview.vim')
call Src('rc/gvim.vim')
call Src('rc/ultisnips.vim')
call Src('rc/gutentags.vim')
call Src('rc/maximizer.vim')
call Src('rc/win-movement.vim')
call Src('rc/localvimrc.vim')
call Src('rc/grepper-functions.vim')
call Src('rc/grepper.vim')
call Src('rc/session.vim')
call Src('rc/quickfix.vim')
call Src('rc/folding.vim')

call Src('rc/refactoring_support.vim')
call Src('rc/refactoring_PL.vim')
call Src('rc/refactoring.vim')

call Src('rc/cmdline.vim')

call Src('rc/myops.vim')
call Src('rc/vimple.vim')

if ! empty(g:adhocinitfile)
    let s:adhocinitfile_after = fnamemodify(g:adhocinitfile, ':r') . '.after.' . fnamemodify(g:adhocinitfile, ':e')
    if filereadable(s:adhocinitfile_after)
        execute 'source ' . fnameescape(s:adhocinitfile_after)
    endif
endif
